export enum UserRoles {
    ADMIN = 'ADMIN',
    CEO = 'CEO',
    PROJECT_MANAGER = 'PROJECT_MANAGER',
    SITE_ENGINEER = 'SITE_ENGINEER',
    PROCUREMENT_OFFICER = 'PROCUREMENT_OFFICER',
    STORE_KEEPER = 'STORE_KEEPER',
    FOREMAN = 'FOREMAN',
    MEDICAL_OFFICER = 'MEDICAL_OFFICER'
}